#Data configuration
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost/cars?useUnicode=yes&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

server:
   port: 8080
